-- Crear base de datos dbZapateria
CREATE DATABASE dbZapateria
DEFAULT CHARACTER SET utf8mb4;

-- Poner en uso
USE dbZapateria;

-- Crear tabla CLIENTE
CREATE TABLE CLIENTE
(
     CODCLI CHAR(4),
     NOMCLI VARCHAR(50),
     APECLI VARCHAR(50),
     CELCLI CHAR(9),
     DNICLI CHAR(8),
     CONSTRAINT  CODCLI_PK PRIMARY KEY (CODCLI)
); 

-- Crear tabla EMPLEADO
CREATE TABLE EMPLEADO
(
     CODEMP CHAR(4),
     NOMEMP VARCHAR(50),
     APEEMP VARCHAR(50),
     CELEMP CHAR(9),
     DNIEMP CHAR(8),
     CONSTRAINT  CODEMP_PK PRIMARY KEY (CODEMP)
); 


-- Crear tabla PROVEEDOR
CREATE TABLE PROVEEDOR
(
     CODPROV CHAR(4),
     NOMPROV VARCHAR(50),
     APEPROV VARCHAR(50),
     CELPROV CHAR(9),
     DNIPROV CHAR(8),
     CONSTRAINT  CODPROV_PK PRIMARY KEY (CODPROV)
); 

-- Crear tabla PRODUCTO
CREATE TABLE PRODUCTO
(
     CODPRO CHAR(4),
     COLPRO VARCHAR(50),
     TALPRO CHAR(2),
     PREPO DECIMAL(10,2),
     TIPPRO VARCHAR(50),
     CODMAR CHAR(4),
     CODPROV CHAR(4),
     CONSTRAINT  CODPRO_PK PRIMARY KEY (CODPRO)
); 

-- Crear tabla MARCA
CREATE TABLE MARCA
(
     CODMAR CHAR(4),
     NOMMAR CHAR(50),
     CONSTRAINT  CODMAR_PK PRIMARY KEY (CODMAR)
); 

-- Crear tabla VENTA
CREATE TABLE VENTA
(
     CODVEN CHAR(4),
     FECVEN DATE,
     CODCLI CHAR(4),
     CODEMP CHAR(4),
     CONSTRAINT  CODVEN_PK PRIMARY KEY (CODVEN)
); 

-- Crear tabla VENTA_DETALLE
CREATE TABLE VENTA_DETALLE
(
     CODVENDET CHAR(4),
     CANVENDET CHAR(4),
     CODPRO CHAR(4),
     CODVEN CHAR(4),
     CONSTRAINT  CODVENDET_PK PRIMARY KEY (CODVENDET)
); 

/* Relaciones de tablas */
-- Relacionar la tabla CLIENTE - VENTA
ALTER TABLE VENTA
ADD CONSTRAINT CLIENTE_VENTA_CODCLI
FOREIGN KEY (CODCLI) REFERENCES CLIENTE (CODCLI);

-- Relacionar la tabla EMPLEADO - VENTA
ALTER TABLE VENTA
ADD CONSTRAINT EMPLEADO_VENTA_CODEMP
FOREIGN KEY (CODEMP) REFERENCES EMPLEADO (CODEMP);

-- Relacionar la tabla PROVEEDOR - PRODUCTO
ALTER TABLE PRODUCTO
ADD CONSTRAINT PROVEEDOR_PRODUCTO_CODPROV
FOREIGN KEY (CODPROV) REFERENCES PROVEEDOR (CODPROV);

-- Relacionar la tabla MARCA - PRODUCTO
ALTER TABLE PRODUCTO
ADD CONSTRAINT MARCA_PRODUCTO_CODMAR
FOREIGN KEY (CODMAR) REFERENCES MARCA (CODMAR);

-- Relacionar la tabla PRODUCTO - VENTA_DETALLE
ALTER TABLE VENTA_DETALLE
ADD CONSTRAINT PRODUCTO_VENTA_DETALLE_CODPRO
FOREIGN KEY (CODPRO) REFERENCES PRODUCTO (CODPRO);

-- Relacionar la tabla VENTA - VENTA_DETALLE
ALTER TABLE VENTA_DETALLE
ADD CONSTRAINT VENTA_VENTA_DETALLE_CODVEN
FOREIGN KEY (CODVEN) REFERENCES VENTA (CODVEN);


